const PRODUCTS=[
{id:1,name:"Velvet Kiss Lip Cream",category:"Lipstik",color:"Rose",price:129000,icon:"💄",rating:4.9,badge:"BEST SELLER",desc:"Lip cream lembut dengan hasil velvet yang nyaman untuk daily look.",shades:["Rose","Nude Pink","Berry"]},
{id:2,name:"Glow Skin Foundation",category:"Foundation",color:"Nude",price:189000,icon:"🧴",rating:4.8,badge:"NEW",desc:"Foundation ringan dengan coverage buildable dan finish natural glow.",shades:["Fair","Light","Medium","Tan"]},
{id:3,name:"Pink Dream Eyeshadow",category:"Eyeshadow",color:"Pink",price:159000,icon:"🎨",rating:4.9,badge:"FAVORITE",desc:"Palet eyeshadow bernuansa pink, nude dan shimmer untuk berbagai look.",shades:["Pink","Rose","Brown"]},
{id:4,name:"Rosy Cheek Blush",category:"Blush On",color:"Pink",price:99000,icon:"🌸",rating:4.8,badge:"HOT",desc:"Blush dengan warna buildable yang memberi efek pipi fresh dan sehat.",shades:["Baby Pink","Rose","Peach"]},
{id:5,name:"Sweet Nude Lip Tint",category:"Lipstik",color:"Nude",price:89000,icon:"💋",rating:4.7,badge:"",desc:"Lip tint ringan dengan warna nude yang cocok untuk tampilan natural.",shades:["Nude","Rose Nude","Brown Nude"]},
{id:6,name:"Blossom Cheek Duo",category:"Blush On",color:"Rose",price:119000,icon:"🌷",rating:4.9,badge:"NEW",desc:"Duo blush untuk hasil soft pink atau rose sesuai mood.",shades:["Soft Pink","Rose"]},
{id:7,name:"Everyday Glow Bundle",category:"Bundle Set",color:"Pink",price:299000,icon:"🎁",rating:5,badge:"SAVE 20%",desc:"Bundle pilihan untuk membuat daily makeup routine lebih praktis.",shades:["Pink Set"]},
{id:8,name:"Rose Gold Eye Kit",category:"Bundle Set",color:"Brown",price:329000,icon:"✨",rating:4.8,badge:"LIMITED",desc:"Set eyeshadow dan beauty essentials dengan nuansa rose gold.",shades:["Rose Gold","Brown"]}];

let cart=JSON.parse(localStorage.getItem("rastyCart")||"[]");

const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
function saveCart(){localStorage.setItem("rastyCart",JSON.stringify(cart));updateCartCount()}
function updateCartCount(){document.querySelectorAll("#cartCount").forEach(e=>e.textContent=cart.reduce((s,x)=>s+x.qty,0))}
function toast(msg){let t=document.querySelector(".toast");if(!t){t=document.createElement("div");t.className="toast";document.body.appendChild(t)}t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function addToCart(id,qty=1){let p=PRODUCTS.find(x=>x.id===id), item=cart.find(x=>x.id===id);item?item.qty+=qty:cart.push({id,qty});saveCart();toast(`${p.name} ditambahkan ke keranjang ♡`);renderCart()}
function removeCart(id){cart=cart.filter(x=>x.id!==id);saveCart();renderCart()}
function renderCart(){let box=document.getElementById("cartItems"),total=document.getElementById("cartTotal");if(!box)return;if(!cart.length){box.innerHTML='<p style="text-align:center;color:#9b7c87;padding:50px 10px">Keranjangmu masih kosong ♡</p>';if(total)total.textContent=rupiah(0);return}let sum=0;box.innerHTML=cart.map(x=>{let p=PRODUCTS.find(y=>y.id===x.id),sub=p.price*x.qty;sum+=sub;return `<div class="drawer-item"><div class="mini-img">${p.icon}</div><div><strong>${p.name}</strong><div>${rupiah(p.price)} × ${x.qty}</div></div><button class="remove" onclick="removeCart(${p.id})">×</button></div>`}).join("");if(total)total.textContent=rupiah(sum)}
function openCart(){document.getElementById("cartDrawer")?.classList.add("open");document.getElementById("overlay")?.classList.add("show");renderCart()}
function closeCart(){document.getElementById("cartDrawer")?.classList.remove("open");document.getElementById("overlay")?.classList.remove("show")}
function openSearch(){document.getElementById("searchModal")?.classList.add("show");document.getElementById("searchInput")?.focus()}
function closeSearch(){document.getElementById("searchModal")?.classList.remove("show")}
function quickSearch(q){let r=document.getElementById("searchResults");if(!r)return;let a=PRODUCTS.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())||p.category.toLowerCase().includes(q.toLowerCase()));r.innerHTML=q?a.map(p=>`<a class="search-item" href="product.html?id=${p.id}">${p.icon} <strong>${p.name}</strong> — ${rupiah(p.price)}</a>`).join(""):""}
function productCard(p){return `<article class="product-card"><button class="wishlist" onclick="toggleWish(${p.id})">♡</button><a href="product.html?id=${p.id}"><div class="product-img">${p.icon}</div></a><div class="product-info"><small>${p.badge||p.category.toUpperCase()}</small><h3>${p.name}</h3><div class="rating">★★★★★ <span>(${p.rating})</span></div><div class="price">${rupiah(p.price)}</div><button class="add-btn" onclick="addToCart(${p.id})">Tambah ke Keranjang</button></div></article>`}
function renderProducts(id,items){let e=document.getElementById(id);if(e)e.innerHTML=items.map(productCard).join("")}
function toggleWish(id){let w=JSON.parse(localStorage.getItem("rastyWish")||"[]");w.includes(id)?w=w.filter(x=>x!==id):w.push(id);localStorage.setItem("rastyWish",JSON.stringify(w));toast(w.includes(id)?"Ditambahkan ke wishlist ♡":"Dihapus dari wishlist")}
function initShop(){let params=new URLSearchParams(location.search);let cf=document.getElementById("categoryFilter");if(params.get("category"))cf.value=params.get("category");["categoryFilter","colorFilter","priceFilter","sortFilter"].forEach(id=>document.getElementById(id)?.addEventListener("input",filterShop));filterShop();updateCartCount()}
function filterShop(){let c=document.getElementById("categoryFilter")?.value||"",co=document.getElementById("colorFilter")?.value||"",max=Number(document.getElementById("priceFilter")?.value||500000),sort=document.getElementById("sortFilter")?.value||"popular";let a=PRODUCTS.filter(p=>(!c||p.category===c)&&(!co||p.color===co)&&p.price<=max);if(sort==="low")a.sort((x,y)=>x.price-y.price);if(sort==="high")a.sort((x,y)=>y.price-x.price);if(sort==="new")a.reverse();renderProducts("shopProducts",a);let rc=document.getElementById("resultCount");if(rc)rc.textContent=a.length;let pv=document.getElementById("priceValue");if(pv)pv.textContent=rupiah(max)}
function resetFilters(){document.getElementById("categoryFilter").value="";document.getElementById("colorFilter").value="";document.getElementById("priceFilter").value=500000;filterShop()}
function initProduct(){let id=Number(new URLSearchParams(location.search).get("id"))||1,p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[0],e=document.getElementById("productDetail");e.innerHTML=`<div class="detail-image">${p.icon}</div><div class="detail-info"><span class="eyebrow">${p.category}</span><h1>${p.name}</h1><div class="rating">★★★★★ ${p.rating}/5</div><div class="detail-price">${rupiah(p.price)}</div><p>${p.desc}</p><h4>Pilih Varian / Shade</h4><div class="shade-list">${p.shades.map((s,i)=>`<button class="shade ${i===0?"active":""}" onclick="selectShade(this)">${s}</button>`).join("")}</div><div class="quantity"><button onclick="changeQty(-1)">−</button><strong id="detailQty">1</strong><button onclick="changeQty(1)">+</button></div><button class="btn" onclick="addToCart(${p.id},Number(document.getElementById('detailQty').textContent));openCart()">Tambah ke Keranjang ♡</button><button class="btn" style="background:#fce8f0;color:#704654" onclick="toggleWish(${p.id})">♡ Wishlist</button><hr style="border:0;border-top:1px solid #f0e1e6;margin:30px 0"><h3>Review Pengguna</h3><p>“Warnanya cantik dan packaging-nya gemas banget!” — Sarah ⭐⭐⭐⭐⭐</p></div>`;renderProducts("relatedProducts",PRODUCTS.filter(x=>x.category===p.category&&x.id!==p.id).slice(0,4));updateCartCount()}
function changeQty(n){let e=document.getElementById("detailQty");if(e)e.textContent=Math.max(1,Number(e.textContent)+n)}
function selectShade(el){document.querySelectorAll(".shade").forEach(x=>x.classList.remove("active"));el.classList.add("active")}
function renderCheckout(){let box=document.getElementById("checkoutItems"),total=document.getElementById("checkoutTotal");if(!box)return;let sum=0;box.innerHTML=cart.map(x=>{let p=PRODUCTS.find(y=>y.id===x.id),sub=p.price*x.qty;sum+=sub;return `<div class="checkout-item"><span>${p.name} × ${x.qty}</span><strong>${rupiah(sub)}</strong></div>`}).join("")||"<p>Keranjang masih kosong.</p>";total.textContent=rupiah(sum)}
function placeOrder(e){e.preventDefault();if(!cart.length){alert("Keranjang masih kosong.");return}alert("Pesanan berhasil dibuat! Terima kasih sudah berbelanja di RASTY BEAUTY ♡");cart=[];saveCart();location.href="index.html"}
function subscribe(e){e.preventDefault();alert("Terima kasih! Kamu sudah berlangganan newsletter RASTY BEAUTY ♡");e.target.reset()}
function sendMessage(e){e.preventDefault();alert("Pesan berhasil dikirim. Tim RASTY BEAUTY akan segera menghubungi kamu ♡");e.target.reset()}
document.addEventListener("DOMContentLoaded",()=>{updateCartCount();renderCart();document.querySelector(".menu-toggle")?.addEventListener("click",()=>document.querySelector(".navbar nav")?.classList.toggle("mobile"))});
